In [4]:
pip install numpy


  Using cached numpy-1.24.2-cp39-cp39-win_amd64.whl (14.9 MB)


In [5]:
import numpy as np

In [9]:
array = np.random.rand(10,3)

In [10]:
print(array)

[[0.96239535 0.12777557 0.22754434]
 [0.30472697 0.39528473 0.80559958]
 [0.26757646 0.94559425 0.02392561]
 [0.48353815 0.10210515 0.84825975]
 [0.3663779  0.97366373 0.67615509]
 [0.66229974 0.82476835 0.04352891]
 [0.1280611  0.64529359 0.69068593]
 [0.3423781  0.85243662 0.30881987]
 [0.3489391  0.73968686 0.6024645 ]
 [0.76591477 0.33140083 0.87697017]]
