In [ ]:
pip install numpy

In [2]:
import numpy as np

In [4]:
array=np.random.rand(10,3)

In [5]:
print(array)

[[0.75663394 0.65155123 0.18359535]
 [0.94595156 0.8115512  0.64297396]
 [0.66140814 0.42145489 0.8116005 ]
 [0.04261249 0.6572613  0.64778206]
 [0.4189705  0.57263815 0.85136777]
 [0.19941063 0.90371781 0.89419551]
 [0.91771871 0.25213038 0.85196165]
 [0.4835017  0.97689316 0.05183483]
 [0.87310181 0.39873516 0.16327984]
 [0.51479459 0.2612269  0.45991702]]
